Import Upstream version 3.3.0

diff --git a/prog/pwm/fancontrol b/prog/pwm/fancontrol
--- a/prog/pwm/fancontrol
+++ b/prog/pwm/fancontrol
@@ -1,28 +1,25 @@
 #!/bin/bash
 #
 # Simple script implementing a temperature dependent fan speed control
+# Supported Linux kernel versions: 2.6.5 and later
 #
-# Version 0.66
+# Version 0.70
 #
 # Usage: fancontrol [CONFIGFILE]
 #
 # Dependencies:
-#   bash, egrep, sed, cut, sleep, lm_sensors :)
+#   bash, egrep, sed, cut, sleep, readlink, lm_sensors :)
 #
 # Please send any questions, comments or success stories to
 # marius.reiner@hdev.de
 # Thanks!
-#
-# The latest version of this script is available at:
-# http://www.hdev.de/fancontrol/fancontrol.html
-# or in the SVN version of lm_sensors
 #
 # For configuration instructions and warnings please see fancontrol.txt, which
 # can be found in the doc/ directory or at the website mentioned above.
 #
 #
 #    Copyright 2003 Marius Reiner <marius.reiner@hdev.de>
-#    Copyright (C) 2007 Jean Delvare <khali@linux-fr.org>
+#    Copyright (C) 2007-2009 Jean Delvare <khali@linux-fr.org>
 #
 #    This program is free software; you can redistribute it and/or modify
 #    it under the terms of the GNU General Public License as published by
@@ -36,21 +33,30 @@
 #
 #    You should have received a copy of the GNU General Public License
 #    along with this program; if not, write to the Free Software
-#    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
+#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
+#    MA 02110-1301 USA.
 #
 #
+
+PIDFILE="/var/run/fancontrol.pid"
 
 #DEBUG=1
 MAX=255
-
-echo $$ > /var/run/fancontrol.pid
 
 declare -i pwmval
 
 function LoadConfig {
 	echo "Loading configuration from $1 ..."
+	if [ ! -r "$1" ]
+	then
+		echo "Error: Can't read configuration file"
+		exit 1
+	fi
+
 	# grep configuration from file
 	INTERVAL=`egrep '^INTERVAL=.*$' $1 | sed -e 's/INTERVAL=//g'`
+	DEVPATH=`egrep '^DEVPATH=.*$' $1 | sed -e 's/DEVPATH= *//g'`
+	DEVNAME=`egrep '^DEVNAME=.*$' $1 | sed -e 's/DEVNAME= *//g'`
 	FCTEMPS=`egrep '^FCTEMPS=.*$' $1 | sed -e 's/FCTEMPS=//g'`
 	MINTEMP=`egrep '^MINTEMP=.*$' $1 | sed -e 's/MINTEMP=//g'`
 	MAXTEMP=`egrep '^MAXTEMP=.*$' $1 | sed -e 's/MAXTEMP=//g'`
@@ -148,6 +154,108 @@ function LoadConfig {
 	echo
 }
 
+function DevicePath()
+{
+	if [ -h "$1/device" ]
+	then
+		readlink -f "$1/device" | sed -e 's/^\/sys\///'
+	fi
+}
+
+function DeviceName()
+{
+	if [ -r "$1/name" ]
+	then
+		cat "$1/name" | sed -e 's/[[:space:]=]/_/g'
+	elif [ -r "$1/device/name" ]
+	then
+		cat "$1/device/name" | sed -e 's/[[:space:]=]/_/g'
+	fi
+}
+
+function ValidateDevices()
+{
+	local OLD_DEVPATH="$1" OLD_DEVNAME="$2" outdated=0
+	local entry device name path
+
+	for entry in $OLD_DEVPATH
+	do
+		device=`echo "$entry" | sed -e 's/=[^=]*$//'`
+		path=`echo "$entry" | sed -e 's/^[^=]*=//'`
+
+		if [ "`DevicePath "$device"`" != "$path" ]
+		then
+			echo "Device path of $device has changed"
+			outdated=1
+		fi
+	done
+
+	for entry in $OLD_DEVNAME
+	do
+		device=`echo "$entry" | sed -e 's/=[^=]*$//'`
+		name=`echo "$entry" | sed -e 's/^[^=]*=//'`
+
+		if [ "`DeviceName "$device"`" != "$name" ]
+		then
+			echo "Device name of $device has changed"
+			outdated=1
+		fi
+	done
+
+	return $outdated
+}
+
+# Check that all referenced sysfs files exist
+function CheckFiles {
+	local outdated=0
+
+	let fcvcount=0
+	while (( $fcvcount < ${#AFCPWM[@]} )) # go through all pwm outputs
+	do
+		pwmo=${AFCPWM[$fcvcount]}
+		if [ ! -w $pwmo ]
+		then
+			echo "Error: file $pwmo doesn't exist"
+			outdated=1
+		fi
+		let fcvcount=$fcvcount+1
+	done
+
+	let fcvcount=0
+	while (( $fcvcount < ${#AFCTEMP[@]} )) # go through all temp inputs
+	do
+		tsen=${AFCTEMP[$fcvcount]}
+		if [ ! -r $tsen ]
+		then
+			echo "Error: file $tsen doesn't exist"
+			outdated=1
+		fi
+		let fcvcount=$fcvcount+1
+	done
+
+	let fcvcount=0
+	while (( $fcvcount < ${#AFCFAN[@]} )) # go through all fan inputs
+	do
+		fan=${AFCFAN[$fcvcount]}
+		if [ ! -r $fan ]
+		then
+			echo "Error: file $fan doesn't exist"
+			outdated=1
+		fi
+		let fcvcount=$fcvcount+1
+	done
+
+	if [ $outdated -eq 1 ]
+	then
+		echo
+		echo "At least one referenced file is missing. Either some required kernel"
+		echo "modules haven't been loaded, or your configuration file is outdated."
+		echo "In the latter case, you should run pwmconfig again."
+	fi
+
+	return $outdated
+}
+
 if [ -f "$1" ]
 then
 	LoadConfig $1
@@ -155,84 +263,94 @@ else
 	LoadConfig /etc/fancontrol
 fi
 
-DIR=/proc/sys/dev/sensors
+# Detect path to sensors
+if echo "${AFCPWM[0]}" | egrep -q '^/'
+then
+	DIR=/
+elif echo "${AFCPWM[0]}" | egrep -q '^hwmon[0-9]'
+then
+	DIR=/sys/class/hwmon
+elif echo "${AFCPWM[0]}" | egrep -q '^[1-9]*[0-9]-[0-9abcdef]{4}'
+then
+	DIR=/sys/bus/i2c/devices
+else
+	echo "$0: Invalid path to sensors"
+	exit 1
+fi
+
 if [ ! -d $DIR ]
 then
-	# For Linux 2.6, detect if config file uses the hwmon class or not yet
-	if echo "${AFCPWM[0]}" | egrep -q '^hwmon[0-9]'
-	then
-		SDIR=/sys/class/hwmon
-	else
-		SDIR=/sys/bus/i2c/devices
-	fi
-
-	if [ ! -d $SDIR ]
-	then
-		echo $0: 'No sensors found! (did you load the necessary modules?)'
-		exit 1
-	else
-		SYSFS=1
-		DIR=$SDIR
-	fi
+	echo $0: 'No sensors found! (did you load the necessary modules?)'
+	exit 1
 fi
 cd $DIR
+
+# Check for configuration change
+if [ -z "$DEVPATH" -o -z "$DEVNAME" ]
+then
+	echo "Configuration is too old, please run pwmconfig again"
+	exit 1
+fi
+if ! ValidateDevices "$DEVPATH" "$DEVNAME"
+then
+	echo "Configuration appears to be outdated, please run pwmconfig again"
+	exit 1
+fi
+CheckFiles || exit 1
+
+if [ -f "$PIDFILE" ]
+then
+	echo "File $PIDFILE exists, is fancontrol already running?"
+	exit 1
+fi
+echo $$ > "$PIDFILE"
 
 # $1 = pwm file name
 function pwmdisable()
 {
-	if [ -n "$SYSFS" ]
+	ENABLE=${1}_enable
+	# No enable file? Just set to max
+	if [ ! -f $ENABLE ]
 	then
-		ENABLE=${1}_enable
-		# No enable file? Just set to max
-		if [ ! -f $ENABLE ]
-		then
-			echo $MAX > $1
-			return 0
-		fi
-
-		# Try pwmN_enable=0
-		echo 0 > $ENABLE 2> /dev/null
-		if [ `cat $ENABLE` -eq 0 ]
-		then
-			# Success
-			return 0
-		fi
-
-		# It didn't work, try pwmN_enable=1 pwmN=255
-		echo 1 > $ENABLE 2> /dev/null
 		echo $MAX > $1
-		if [ `cat $ENABLE` -eq 1 -a `cat $1` -ge 190 ]
-		then
-			# Success
-			return 0
-		fi
-
-		# Nothing worked
-		echo "$ENABLE stuck to" `cat $ENABLE` >&2
-		return 1
-	else
-		echo $MAX 0 > $1
+		return 0
 	fi
+
+	# Try pwmN_enable=0
+	echo 0 > $ENABLE 2> /dev/null
+	if [ `cat $ENABLE` -eq 0 ]
+	then
+		# Success
+		return 0
+	fi
+
+	# It didn't work, try pwmN_enable=1 pwmN=255
+	echo 1 > $ENABLE 2> /dev/null
+	echo $MAX > $1
+	if [ `cat $ENABLE` -eq 1 -a `cat $1` -ge 190 ]
+	then
+		# Success
+		return 0
+	fi
+
+	# Nothing worked
+	echo "$ENABLE stuck to" `cat $ENABLE` >&2
+	return 1
 }
 
 # $1 = pwm file name
 function pwmenable()
 {
-	if [ "$SYSFS" = "1" ]
+	ENABLE=${1}_enable
+	if [ -f $ENABLE ]
 	then
-		ENABLE=${1}_enable
-		if [ -f $ENABLE ]
+		echo 1 > $ENABLE 2> /dev/null
+		if [ $? -ne 0 ]
 		then
-			echo 1 > $ENABLE 2> /dev/null
-			if [ $? -ne 0 ]
-			then
-				return 1
-			fi
+			return 1
 		fi
-		echo $MAX > $1
-	else
-		echo $MAX 1 > $1
 	fi
+	echo $MAX > $1
 }
 
 function restorefans()
@@ -247,6 +365,7 @@ function restorefans()
 		let fcvcount=$fcvcount+1
 	done
 	echo 'Verify fans have returned to full speed'
+	rm -f "$PIDFILE"
 	exit $status
 }
 
@@ -262,8 +381,8 @@ function UpdateFanSpeeds {
 		pwmo=${AFCPWM[$fcvcount]}
 		tsens=${AFCTEMP[$fcvcount]}
 		fan=${AFCFAN[$fcvcount]}
-		mint=${AFCMINTEMP[$fcvcount]}
-		maxt=${AFCMAXTEMP[$fcvcount]}
+		let mint="${AFCMINTEMP[$fcvcount]}*1000"
+		let maxt="${AFCMAXTEMP[$fcvcount]}*1000"
 		minsa=${AFCMINSTART[$fcvcount]}
 		minso=${AFCMINSTOP[$fcvcount]}
 		minpwm=${AFCMINPWM[$fcvcount]}
@@ -275,22 +394,12 @@ function UpdateFanSpeeds {
 			echo "Error reading temperature from $DIR/$tsens"
 			restorefans 1
 		fi
-		if [ "$SYSFS" = "1" ]
-		then
-			let tval="($tval+500)/1000"
-		else
-			tval=`echo ${tval} | cut -d' ' -f3 | cut -d'.' -f1`
-		fi
 
 		read pwmpval < ${pwmo}
 		if [ $? -ne 0 ]
 		then
 			echo "Error reading PWM value from $DIR/$pwmo"
 			restorefans 1
-		fi
-		if [ "$SYSFS" != "1" ]
-		then
-			pwmpval=`echo ${pwmpval} | cut -d' ' -f1`
 		fi
 
 		# If fanspeed-sensor output shall be used, do it
@@ -301,10 +410,6 @@ function UpdateFanSpeeds {
 			then
 				echo "Error reading Fan value from $DIR/$fan"
 				restorefans 1
-			fi
-			if [ "$SYSFS" != "1" ]
-			then
-				fanval=`echo ${fanval} | cut -d' ' -f2`
 			fi
 		else
 			fanval=1  # set it to a non zero value, so the rest of the script still works
